FROM python:3.8-bullseye

WORKDIR /app

COPY . .

RUN pip install --upgrade pip

RUN pip3 install -r requirements.txt
RUN pip3 install -e .

CMD ["flask", "--app", "backend/app.py", "run", "--host=0.0.0.0"]
